# Generated by Django 2.1.7 on 2019-03-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('put_date', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
